# Generated by Django 2.1.5 on 2020-04-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200401_0541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trap',
            new_name='Traps',
        ),
    ]
