# Generated by Django 2.1.5 on 2020-04-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200401_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traps',
            name='created',
        ),
    ]
